# Generated by Django 2.2.12 on 2020-06-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ss_decisions',
            },
        ),
        migrations.CreateModel(
            name='DecisionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ss_decision_reasons',
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Disease')),
            ],
            options={
                'db_table': 'ss_risk_factors',
            },
        ),
        migrations.CreateModel(
            name='TravellerRiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secondary_screening.RiskFactor')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'ss_traveller_risk_factors',
            },
        ),
        migrations.CreateModel(
            name='TravellerDecisionTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created At Date')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secondary_screening.Decision')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'ss_traveller_decision_taken',
            },
        ),
        migrations.CreateModel(
            name='TravellerDecisionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secondary_screening.DecisionReason')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'ss_traveller_decision_reasons',
            },
        ),
        migrations.CreateModel(
            name='ScreeningTravellerSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Symptom')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'ss_traveller_symptoms',
            },
        ),
    ]
