# Generated by Django 2.2.13 on 2020-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_screening', '0006_auto_20200615_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='decision',
            field=models.CharField(choices=[('Denied', 'Denied /Delayed Travel'), ('Allowed', 'Allowed to Proceed with entry/Exit formalities'), ('Conditional', 'Allowed to proceed with condition')], default='MC', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='reason',
            field=models.CharField(choices=[('OTHER', 'Other'), ('NOT RELATED', 'Illness not related to PRIORITY DISEASE and the traveler obtain medical care at PoE and can continue with travel'), ('REFERRAL', 'Referred to a nearby health facility because the Illness is not related to PRIORITY DISEASE and require other treatment'), ('HIGH RISK CONTACT', 'Referred to contact tracing because met the criteria for high risk contact'), ('SUSPECT CASE', 'Moved to Holding Facility because met the criteria for Suspect Case of PRIORITY DISEASE (complete contact listing form'), ('LABORATORY TESTING', 'Waiting for Laboratory specimen taken and sent to laboratory for testing for PRIORITY DISEASE'), ('LOW EXPOSURE', 'Exposure to PRIORITY DISEASE is low and the traveler can continue travelling while self-monitoring')], default='MC', max_length=50),
        ),
    ]
