# Generated by Django 2.2.13 on 2020-09-08 12:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_screening', '0008_auto_20200907_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasesurveyans',
            options={'verbose_name_plural': 'Disease Survey Answers'},
        ),
        migrations.AlterModelOptions(
            name='diseasesurveyqns',
            options={'verbose_name_plural': 'Disease Survey Questions'},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'verbose_name_plural': 'Risks Assessment'},
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='decision',
            field=models.CharField(choices=[('Denied', 'Denied /Delayed Travel'), ('Allowed', 'Allowed to Proceed with entry/Exit formalities'), ('Conditional', 'Allowed to proceed with condition')], default='Denied', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='reason',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NOT RELATED', 'Illness not related to PRIORITY DISEASE and the traveler obtain medical care at PoE and can continue with travel'), ('OTHER', 'Other'), ('SUSPECT CASE', 'Moved to Holding Facility because met the criteria for Suspect Case of PRIORITY DISEASE (complete contact listing form'), ('HIGH RISK CONTACT', 'Referred to contact tracing because met the criteria for high risk contact'), ('REFERRAL', 'Referred to a nearby health facility because the Illness is not related to PRIORITY DISEASE and require other treatment'), ('LABORATORY TESTING', 'Waiting for Laboratory specimen taken and sent to laboratory for testing for PRIORITY DISEASE'), ('LOW EXPOSURE', 'Exposure to PRIORITY DISEASE is low and the traveler can continue travelling while self-monitoring')], max_length=89),
        ),
    ]
