# Generated by Django 2.2.12 on 2020-05-30 22:05

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalTraveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('sex', models.CharField(choices=[('none', '--Select--'), ('male', 'MALE'), ('female', 'FEMALE')], default='none', max_length=15)),
                ('age', models.PositiveIntegerField(max_length=4)),
                ('passport_no', models.CharField(max_length=250)),
                ('vehicle_flight_vehicle', models.CharField(max_length=250)),
                ('nationality', models.CharField(default='Tanzania', max_length=150)),
                ('mode_of_transport', models.CharField(choices=[('none', '--Select--'), ('flight', 'FLIGHT'), ('vehicle', 'VEHICLE'), ('vessel', 'VESSEL')], default='none', max_length=30)),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('seat_no', models.CharField(max_length=30)),
                ('point_of_entry', models.CharField(max_length=250)),
                ('visit_purpose', models.CharField(choices=[('none', '--Select--'), ('resident', 'RESIDENT'), ('tourist', 'TOURIST'), ('transit', 'TRANSIT'), ('business', 'BUSINESS')], default='none', max_length=45)),
                ('other_purpose', models.TextField()),
                ('duration_for_stay', models.PositiveIntegerField(max_length=4)),
                ('employment', models.CharField(choices=[('none', '--Select--'), ('government', 'GOVERNMENT'), ('non-government', 'NON-GOVERNMENT'), ('non-profit', 'NON-PROFIT'), ('student', 'STUDENT'), ('business', 'BUSINESS'), ('religious', 'RELIGIOUS')], default='none', max_length=45)),
                ('other_employment', models.CharField(max_length=255)),
                ('physical_address', models.TextField()),
                ('hotel_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('street_or_ward', models.CharField(max_length=255)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31, null=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('country_journey_started', models.CharField(default='Tanzania', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TravellerSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='screening.Conditions')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalTravellerExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Tanzania', max_length=150)),
                ('location_visited', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='Date')),
                ('days', models.PositiveIntegerField(max_length=4)),
                ('international_traveller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='travellers.InternationalTraveller')),
            ],
        ),
    ]
