# Generated by Django 2.2.13 on 2020-09-09 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Diseases',
                'db_table': 'et_diseases',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5, null=True)),
                ('parent', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'et_locations',
            },
        ),
        migrations.CreateModel(
            name='PointOfEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mode_of_transport', models.CharField(choices=[('flight', 'Flight'), ('vehicle', 'Vehicle'), ('vessel', 'Vessel'), ('train', 'Train')], max_length=50, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Point of Entries',
                'db_table': 'et_point_of_entries',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en_us', models.CharField(max_length=100, null=True)),
                ('title_sw', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'et_symptoms',
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at Date')),
                ('full_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('international', 'INTERNATIONAL'), ('domestic', 'DOMESTIC')], default='none', max_length=25)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='none', max_length=15)),
                ('age', models.IntegerField(null=True)),
                ('nationality', models.IntegerField(default=-1, null=True)),
                ('id_type', models.CharField(choices=[('passport-number', 'PASSPORT NUMBER'), ('national-id', 'NATIONAL ID'), ('voter-id', 'VOTER ID')], default='none', max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('employment', models.CharField(choices=[('government', 'Government'), ('non-government', 'Non-Government'), ('non-profit', 'Non-Profit'), ('student', 'Student'), ('business', 'Business'), ('religious', 'Religious'), ('farmers', 'Farmer')], default='none', max_length=45)),
                ('other_employment', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_transport', models.CharField(choices=[('flight', 'Flight'), ('vehicle', 'Vehicle'), ('vessel', 'Vessel'), ('train', 'Train')], default='none', max_length=30)),
                ('name_of_transport', models.CharField(max_length=30)),
                ('seat_no', models.CharField(max_length=30, null=True)),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('visiting_purpose', models.CharField(choices=[('resident', 'Resident'), ('tourist', 'Tourist'), ('transit', 'Transit'), ('business', 'Business')], default='none', max_length=45)),
                ('other_purpose', models.TextField(null=True)),
                ('duration_of_stay', models.PositiveIntegerField(default=0, null=True)),
                ('physical_address', models.TextField(null=True)),
                ('hotel_name', models.CharField(max_length=255, null=True)),
                ('region_id', models.IntegerField(default=-1, null=True)),
                ('district_id', models.IntegerField(default=-1, null=True)),
                ('street_or_ward', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(default='None', max_length=25)),
                ('email', models.EmailField(default='None', max_length=255)),
                ('temp', models.FloatField(null=True)),
                ('disease_to_screen', models.CharField(default='0', max_length=150)),
                ('action_taken', models.CharField(default='None', max_length=100)),
                ('other_symptoms', models.TextField(null=True)),
                ('accept', models.IntegerField(default=0, null=True)),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated At Date')),
                ('location_origin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Location')),
                ('point_of_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.PointOfEntry')),
            ],
            options={
                'db_table': 'et_travellers',
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravellerVisitedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_visited', models.CharField(max_length=250, null=True)),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('days', models.PositiveIntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Location')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_visited_areas',
            },
        ),
        migrations.CreateModel(
            name='TravellerSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Symptom')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_symptoms',
            },
        ),
        migrations.CreateModel(
            name='ScreenCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=1)),
                ('countries', models.ManyToManyField(blank=True, related_name='countries', to='travellers.Location')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Disease')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='symptoms', to='travellers.Symptom')),
            ],
            options={
                'db_table': 'et_ss_criteria',
            },
        ),
        migrations.CreateModel(
            name='LocationDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Location')),
            ],
            options={
                'db_table': 'et_location_diseases',
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Symptom')),
            ],
            options={
                'db_table': 'et_disease_symptoms',
            },
        ),
    ]
