# Generated by Django 2.2.13 on 2020-12-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='district_id',
        ),
        migrations.AddField(
            model_name='traveller',
            name='district',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='district', to='travellers.Location'),
        ),
        migrations.AlterField(
            model_name='pointofentry',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('', '-- Select --'), ('flight', 'Flight'), ('truck', 'Truck'), ('bus', 'Bus'), ('vehicle', 'Vehicle'), ('vessel', 'Vessel'), ('train', 'Train'), ('by-foot', 'By Foot')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='age_category',
            field=models.CharField(choices=[('', '-- Select --'), ('above', 'ABOVE 1'), ('below', 'BELOW 1')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='duration_of_stay',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='employment',
            field=models.CharField(choices=[('', '-- Select --'), ('student', 'Student'), ('religious', 'Religious'), ('farmer', 'Farmer'), ('hunter', 'Hunter'), ('nurse', 'Nurse'), ('clinician', 'Clinician'), ('engineer', 'Engineer'), ('sports', 'Sports'), ('business', 'Business'), ('other', 'Other')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='mode_of_transport',
            field=models.CharField(choices=[('', '-- Select --'), ('flight', 'Flight'), ('truck', 'Truck'), ('bus', 'Bus'), ('vehicle', 'Vehicle'), ('vessel', 'Vessel'), ('train', 'Train'), ('by-foot', 'By Foot')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='sex',
            field=models.CharField(choices=[('', '-- Select --'), ('M', 'Male'), ('F', 'Female')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='street_or_ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='visiting_purpose',
            field=models.CharField(choices=[('', '-- Select --'), ('resident', 'Resident'), ('tourist', 'Tourist'), ('diplomat', 'Diplomat'), ('transit', 'Transit'), ('business', 'Business'), ('conference', 'Conference'), ('studies', 'Studies'), ('other', 'Other')], default='None', max_length=50),
        ),
    ]
