# Generated by Django 2.2.13 on 2020-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasesymptom',
            options={'verbose_name_plural': 'Disease Sysmptoms'},
        ),
        migrations.AlterModelOptions(
            name='screencriteria',
            options={'verbose_name_plural': 'Screening Criteria'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name_plural': 'Symptoms'},
        ),
        migrations.AlterField(
            model_name='symptom',
            name='alias',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
