# Generated by Django 2.2.12 on 2020-05-30 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationaltraveller',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='internationaltravellerext',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='travellersymptom',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='internationaltraveller',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internationaltraveller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaltravellerext',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internationaltravellerext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travellersymptom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travellersymptom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internationaltraveller',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='internationaltraveller',
            name='duration_for_stay',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='internationaltravellerext',
            name='days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='internationaltraveller',
            table='international_traveller',
        ),
        migrations.AlterModelTable(
            name='internationaltravellerext',
            table='international_traveller_ext',
        ),
        migrations.AlterModelTable(
            name='travellersymptom',
            table='traveller_conditions',
        ),
    ]
