# Generated by Django 2.2.13 on 2020-09-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0002_auto_20200806_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='title_sw',
        ),
    ]
