# Generated by Django 2.2.13 on 2020-12-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0002_auto_20201214_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='district', to='travellers.Location'),
        ),
    ]
