# Generated by Django 2.2.12 on 2020-06-01 11:00

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0003_auto_20200531_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'et_diseases',
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Disease')),
            ],
            options={
                'db_table': 'et_disease_symptoms',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('parent', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'et_locations',
            },
        ),
        migrations.CreateModel(
            name='LocationDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Disease')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Location')),
            ],
            options={
                'db_table': 'et_location_diseases',
            },
        ),
        migrations.CreateModel(
            name='PointOfEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('region_id', models.PositiveIntegerField()),
                ('mode_of_transport', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Location')),
            ],
            options={
                'db_table': 'et_point_of_entries',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'et_symptoms',
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at Date')),
                ('full_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('none', '--Select--'), ('international', 'INTERNATIONAL'), ('domestic', 'DOMESTIC')], default='none', max_length=25)),
                ('sex', models.CharField(choices=[('none', '--Select--'), ('male', 'MALE'), ('female', 'FEMALE')], default='none', max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('id_type', models.CharField(choices=[('none', '--Select--'), ('passport-number', 'PASSPORT NUMBER'), ('national-id', 'NATIONAL ID'), ('voter-id', 'VOTER ID')], default='none', max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('employment', models.CharField(choices=[('none', '--Select--'), ('government', 'GOVERNMENT'), ('non-government', 'NON-GOVERNMENT'), ('non-profit', 'NON-PROFIT'), ('student', 'STUDENT'), ('business', 'BUSINESS'), ('religious', 'RELIGIOUS')], default='none', max_length=45)),
                ('other_employment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'et_travellers',
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravellerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.TextField()),
                ('hotel_name', models.CharField(max_length=255)),
                ('region_id', models.PositiveIntegerField()),
                ('district_id', models.PositiveIntegerField()),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact Phone Number', max_length=31, null=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('street_or_ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Location')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_contacts',
            },
        ),
        migrations.CreateModel(
            name='TravellerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_transport', models.CharField(choices=[('none', '--Select--'), ('flight', 'FLIGHT'), ('vehicle', 'VEHICLE'), ('vessel', 'VESSEL')], default='none', max_length=30)),
                ('name_of_transport', models.CharField(max_length=30)),
                ('seat_no', models.CharField(max_length=30)),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('point_of_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.PointOfEntry')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_entries',
            },
        ),
        migrations.CreateModel(
            name='TravellerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_temp', models.PositiveIntegerField()),
                ('temp', models.IntegerField()),
                ('action_taken', models.CharField(max_length=50)),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_scores',
            },
        ),
        migrations.CreateModel(
            name='TravellerSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=50)),
                ('other', models.TextField()),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_symptoms',
            },
        ),
        migrations.CreateModel(
            name='TravellerVisitedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_visited', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='Date')),
                ('days', models.PositiveIntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Location')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_visited_areas',
            },
        ),
        migrations.CreateModel(
            name='TravellerVisitingPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('none', '--Select--'), ('resident', 'RESIDENT'), ('tourist', 'TOURIST'), ('transit', 'TRANSIT'), ('business', 'BUSINESS')], default='none', max_length=45)),
                ('other', models.TextField()),
                ('duration_of_stay', models.PositiveIntegerField()),
                ('location_origin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Location')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Traveller')),
            ],
            options={
                'db_table': 'et_traveller_visiting_purposes',
            },
        ),
        migrations.RemoveField(
            model_name='internationaltravellerext',
            name='international_traveller',
        ),
        migrations.RemoveField(
            model_name='travellersymptom',
            name='condition',
        ),
        migrations.DeleteModel(
            name='InternationalTraveller',
        ),
        migrations.DeleteModel(
            name='InternationalTravellerExt',
        ),
        migrations.DeleteModel(
            name='TravellerSymptom',
        ),
        migrations.AddField(
            model_name='diseasesymptom',
            name='symptom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travellers.Symptom'),
        ),
    ]
