# Generated by Django 2.2.13 on 2020-12-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0003_auto_20201214_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='district',
        ),
        migrations.AddField(
            model_name='traveller',
            name='district_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
