# Generated by Django 2.2.13 on 2020-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0003_auto_20200907_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='pointofentry',
            options={'verbose_name_plural': 'Point of Entries'},
        ),
        migrations.AddField(
            model_name='symptom',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pointofentry',
            name='mode_of_transport',
            field=models.CharField(choices=[('flight', 'Flight'), ('vehicle', 'Vehicle'), ('vessel', 'Vessel'), ('train', 'Train')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='employment',
            field=models.CharField(choices=[('government', 'Government'), ('non-government', 'Non-Government'), ('non-profit', 'Non-Profit'), ('student', 'Student'), ('business', 'Business'), ('religious', 'Religious'), ('farmers', 'Farmer')], default='none', max_length=45),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='mode_of_transport',
            field=models.CharField(choices=[('flight', 'Flight'), ('vehicle', 'Vehicle'), ('vessel', 'Vessel'), ('train', 'Train')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='visiting_purpose',
            field=models.CharField(choices=[('resident', 'Resident'), ('tourist', 'Tourist'), ('transit', 'Transit'), ('business', 'Business')], default='none', max_length=45),
        ),
    ]
