# Generated by Django 2.2.12 on 2020-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0004_auto_20200601_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='other_employment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
