# Generated by Django 2.2.13 on 2020-12-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0004_auto_20201214_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='district_id',
        ),
        migrations.AddField(
            model_name='traveller',
            name='district',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travellers.Location'),
        ),
    ]
