# Generated by Django 2.2.13 on 2020-09-09 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travellers', '0004_auto_20200908_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofentry',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='screencriteria',
            name='countries',
        ),
        migrations.AddField(
            model_name='screencriteria',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='countries', to='travellers.Location'),
        ),
        migrations.RemoveField(
            model_name='screencriteria',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='screencriteria',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, related_name='symptoms', to='travellers.Symptom'),
        ),
        migrations.AlterField(
            model_name='screencriteria',
            name='temp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
