# Generated by Django 2.2.13 on 2020-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0005_auto_20200603_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='type',
            field=models.CharField(choices=[('international', 'INTERNATIONAL'), ('domestic', 'DOMESTIC')], default='none', max_length=25),
        ),
    ]
