# Generated by Django 2.2.13 on 2020-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0006_auto_20200603_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='employment',
            field=models.CharField(choices=[('government', 'GOVERNMENT'), ('non-government', 'NON-GOVERNMENT'), ('non-profit', 'NON-PROFIT'), ('student', 'STUDENT'), ('business', 'BUSINESS'), ('religious', 'RELIGIOUS')], default='none', max_length=45),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='id_type',
            field=models.CharField(choices=[('passport-number', 'PASSPORT NUMBER'), ('national-id', 'NATIONAL ID'), ('voter-id', 'VOTER ID')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='sex',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='travellerentry',
            name='mode_of_transport',
            field=models.CharField(choices=[('flight', 'FLIGHT'), ('vehicle', 'VEHICLE'), ('vessel', 'VESSEL')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='travellervisitingpurpose',
            name='purpose',
            field=models.CharField(choices=[('resident', 'RESIDENT'), ('tourist', 'TOURIST'), ('transit', 'TRANSIT'), ('business', 'BUSINESS')], default='none', max_length=45),
        ),
    ]
