# Generated by Django 2.2.14 on 2020-08-06 13:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='decision',
            field=models.CharField(choices=[('Conditional', 'Allowed to proceed with condition'), ('Allowed', 'Allowed to Proceed with entry/Exit formalities'), ('Denied', 'Denied /Delayed Travel')], default='Denied', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='reason',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OTHER', 'Other'), ('NOT RELATED', 'Illness not related to PRIORITY DISEASE and the traveler obtain medical care at PoE and can continue with travel'), ('SUSPECT CASE', 'Moved to Holding Facility because met the criteria for Suspect Case of PRIORITY DISEASE (complete contact listing form'), ('LABORATORY TESTING', 'Waiting for Laboratory specimen taken and sent to laboratory for testing for PRIORITY DISEASE'), ('HIGH RISK CONTACT', 'Referred to contact tracing because met the criteria for high risk contact'), ('LOW EXPOSURE', 'Exposure to PRIORITY DISEASE is low and the traveler can continue travelling while self-monitoring'), ('REFERRAL', 'Referred to a nearby health facility because the Illness is not related to PRIORITY DISEASE and require other treatment')], max_length=89),
        ),
    ]
