# Generated by Django 2.2.12 on 2020-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='perms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module_link',
            name='perms',
            field=models.TextField(default=''),
        ),
    ]
