# Generated by Django 2.2.13 on 2020-09-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('countries', models.CharField(max_length=220)),
                ('symptoms', models.CharField(max_length=220)),
                ('active', models.BooleanField(default=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disease', to='travellers.Disease')),
            ],
            options={
                'db_table': 'et_screen_criteria',
            },
        ),
    ]
