# Generated by Django 2.2.12 on 2020-05-30 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditions',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='conditions',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conditions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conditions',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='conditions',
            table='conditions',
        ),
    ]
