# Generated by Django 2.2.12 on 2020-06-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0004_auto_20200601_1400'),
        ('screening', '0002_auto_20200531_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conditions',
        ),
    ]
