# Generated by Django 2.2.13 on 2020-09-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='title_sw',
        ),
    ]
