# Generated by Django 2.2.13 on 2020-09-08 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='screencriteria',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=50),
        ),
        migrations.AlterField(
            model_name='screencriteria',
            name='symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=50),
        ),
    ]
