# Generated by Django 2.2.13 on 2020-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='screencriteria',
            name='countries',
        ),
        migrations.AddField(
            model_name='screencriteria',
            name='countries',
            field=models.ManyToManyField(related_name='countries', to='travellers.Location'),
        ),
        migrations.RemoveField(
            model_name='screencriteria',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='screencriteria',
            name='symptoms',
            field=models.ManyToManyField(related_name='symptoms', to='travellers.Symptom'),
        ),
    ]
