# Generated by Django 2.2.13 on 2020-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='screencriteria',
            name='countries',
            field=models.ManyToManyField(null=True, related_name='countries', to='travellers.Location'),
        ),
        migrations.AlterField(
            model_name='screencriteria',
            name='symptoms',
            field=models.ManyToManyField(null=True, related_name='symptoms', to='travellers.Symptom'),
        ),
    ]
