# Generated by Django 2.2.13 on 2020-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='screencriteria',
            name='temp',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
